### ISSUE TITLE
Resource not foud

### ISSUE THREAD

**Issue by hugodelaroza** [custom-cards/canvas-gauge-card#1]
Hi, I downloadesr the two .js files and placed them in \config\www\custom_cards folder, then added this to my configuration file:
resources:

  - url: /local/custom_cards/canvas-gauge-card.js
    type: module

and this to my ui-lovelace file:

      - type: custom:canvas-gauge-card
        entity: sensor.processor_use
        name: Processor (%)
        card_height: 145
        shadow_height: 15%
        font_size: 1em
        gauge:
          type: "radial-gauge"
          width: 220
          height: 220
          minValue: 0
          maxValue: 100
          startAngle: 90
          ticksAngle: 180
          valueBox: false
          majorTicks: ["0", "10", "20", "30", "40", "50", "60", "70", "80", "90", "100"]
          minorTicks: 2
          strokeTicks: true
          highlights: [{"from": 80, "to": 100,"color": "rgba(200, 50, 50, .75)"}]
          borders: false   

but when I click on check config, I recive this:

Configuration invalid
Component not found: resources

Can you help me?

**Comment by ludeeus** [comment]
@hugodelaroza 
Add this to the top of your `ui-lovelace.yaml` file not `configuration.yaml`

```yaml
resources:
  - url: /local/custom_cards/canvas-gauge-card.js
    type: module
```

**Comment by hugodelaroza** [comment]
Thank's ludeeus, now works!!
