### ISSUE TITLE
Feature: Adapt card background color to theme

### ISSUE THREAD

**Issue by sgofferj** [custom-cards/canvas-gauge-card#13]
It would be beautiful if the card background color wouldn't be hardcoded to white but would adapt to the current theme.

I did this by replacing line 70 in canvas-gauge-card.js:
```
background-color: white !important;
```
with
```
background-color: var( --ha-card-background, var(--paper-card-background-color, white) ); !important;
```

**Comment by 4sag** [comment]
not working (

**Comment by sgofferj** [comment]
On a running system there's also canvas-gauge-card.js.gz which seems to be preferred. So if you change the .js you also have to gzip it into the js.gz.

**Comment by browetd** [comment]
Thank you for the post... It is working for me (in a venv, HA 0.102.0) !

**Comment by dohlin** [comment]
I'm clearly missing something here...I tried both noted "background-color" options, with full reboots of my HA VM in between, as well as looking everywhere within the docker container config directory for the mentioned "canvas-gauge-card.js.gz" file which I do not see.  Regardless the background is still white.  Running an Ubuntu 18.04 VM w/ a HASS.io docker container inside.  Anyone have any thoughts as to what I can try?  Thanks!

**Comment by helto4real** [comment]
I will try to make it configurable instead.

**Comment by helto4real** [comment]
Working copy now published, I changed the build system so the actual js file is in release not in src folder. Also now just need the one file since all dependencies are merged in build.
The background color is configurable through yaml, see docs.
