### ISSUE TITLE
Error: gauge.min.js

### ISSUE THREAD

**Issue by bussio** [custom-cards/canvas-gauge-card#16]
From HA 0.106.0b0 on I get
following error message:

"Protocol details (ERROR)
Logger: hacs
First occured: February 22, 2020, 5:40:11 pm (8 occurences)
Last logged: 11:28:29
Tried to serve up '/config/www/community/canvas-gauge-card/gauge.min.js' but it does not exist"

As a result, the map is not displayed correctly.

**Comment by helto4real** [comment]
There is a fix in the #18 issue, please test if you can.

**Comment by bussio** [comment]
Thanks for your fix but after the update I get the following error message when displaying:
"Attempted to assign to readonly property."

**Comment by tnagels** [comment]
When installing 0.2.0 via HACS I also still get this error. Even when adding the file manually the gauges do not work.

**Comment by bussio** [comment]
With the new 0.3.0 installed over HACS it works again. Thank you for your work.

**Comment by helto4real** [comment]
Awesome thanks! @bussio
