### ISSUE TITLE
error

### ISSUE THREAD

**Issue by womp666** [custom-cards/canvas-gauge-card#23]
downloaded both JS files to /www/JS folder
added url lines in new love-lace dashboards-resources
copied 1st sample code and changed to one of my sensors using manual card, had to remove dash and 2 spaces 
I get this at the top of the window and shows code instead a gauge
Cannot assign to read only property 'borderShadowWidth' of object '#<Object>'

**Comment by womp666** [comment]
It is working after removed the bottom line 
  borders: false

**Comment by helto4real** [comment]
Ok good closing issue
