### ISSUE TITLE
 changing colors?

### ISSUE THREAD

**Issue by jaygrovr** [custom-cards/canvas-gauge-card#25]
Has anyone tried to change colors of the dials/gauges?  I cannot seem to get this to work.  If someone can provide an example. that would be great.

I have tried the following
background_color: 'rgba(0, 0, 250, 1)'
data-color-plate: "#222"

But I havent been able to get it to change anything.  I wanted a black background, or even gray.

**Comment by jaygrovr** [comment]
i got it..  it has to be colorPlate and then it works.. sorry for the confusion.

**Comment by helto4real** [comment]
Closing since it is solved.
