### ISSUE TITLE
Error on Home Assistant 0.109.3

### ISSUE THREAD

**Issue by msslava** [custom-cards/canvas-gauge-card#28]
Hi, after create card with canvas-gauge-card.js happens error:

![canvas-error](https://user-images.githubusercontent.com/3504940/80939443-50bfdd80-8de5-11ea-9642-d407d131da36.png)

frontent does not display anything, the main screen is blank.

**Comment by helto4real** [comment]
How did you install it? I recommend using HACS, if not make sure you grabbed the version from here: 
https://github.com/custom-cards/canvas-gauge-card/releases/tag/0.2

**Comment by msslava** [comment]
Sorry, I think I found the problem on my part
