### ISSUE TITLE
Missing entity renders dashboard page empty

### ISSUE THREAD

**Issue by alexelite** [custom-cards/canvas-gauge-card#29]
Hello and thanks for making this plugin.
I have a fresh install of Home Assistant and I added canvas-gauge-card through HACS.
In lovelace I added the first example "Example 3, simple full gauge with shadow text", changed the indentation and the entity sensors name, and it worked. 
But I noticed that if the entity does not exist, the whole dashboard page is not rendered any more. Looks like a blank page, even if there are other card, regardless of their type.

**Comment by helto4real** [comment]
It must be something with the new version. I will look into the issue

**Comment by helto4real** [comment]
The latests pre-release 0.3 should fix it. Make sure you have pre-release settings in HACS. The reason I did a pre-release is that I hade to recfator the whole thing. Need testing.
People not running HACS download it here
https://github.com/custom-cards/canvas-gauge-card/releases/tag/0.3

**Comment by alexelite** [comment]
I installed version 0.3 and now it shows a blank card when the sensor definition is wrong. No more blank page. Thank you.
