### ISSUE TITLE
RadialGauge is not supported 

### ISSUE THREAD

**Issue by dusankeprta** [custom-cards/canvas-gauge-card#3]
Please , could you advice when I am receiving   RadialGauge is not supported ?
Initial configuration 
     - type: custom:canvas-gauge-card
        entity: sensor.X.X.X.
        card_height: 125
        gauge:
          type: "radial-gauge"

Thank you

**Comment by rpitera** [comment]
Radial Gauges are supported for sure; I'm using one for a compass and it's working fine.  The styling is totally screwed now with the last PR from @iantrich but the compass itself still works.

**Comment by AndyAnka** [comment]
I seem to have the same problem. I tried the example code with the compass without any luck.
I have downloaded the two js files in my local folder, defined the resource in my ui Lovelace file.
/Anders

**Comment by helto4real** [comment]
I use the radial myself. Try the latest version of the js file you find it under latest release (don´t download the one under src. You now require only that file since all dependecies are compiled in one file.
