### ISSUE TITLE
Is it possible for the text to show the "group by" value, not the raw value?

### ISSUE THREAD

**Issue by mike-berriman** [custom-cards/canvas-gauge-card#32]
My rainfall sensor reports every 5 minutes with the rain that's fallen in that 5 minute interval.  So I've configured my chart using "group by: Day".  Works awesome.

What I would like however is for the text shown to also show the current day's rainfall.  At the moment it shows the sensor data, which is the rainfall for the current 5 minutes.  I can only get the daily total by hovering over the last bar in the bar chart.

Is this possible to configure, or is it an enhancement request?

**Comment by helto4real** [comment]
It always shows the sensor data, it would be a new feature to show something else, like an attribute.
