### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by Protoncek** [custom-cards/canvas-gauge-card#40]
Hi!
I'm pretty new to HA, so i have some problems: i just can't get this plugin to work. I installed it through HACS, i entered yaml mode in "configuration.yaml", I created ui-lovelace.yaml, transfered my current dashboard so that part works. I just can't add this gauge no matter what. I keep getting errors, like "type: module" is unknow type encountered.

What am i missing? Did i forgot to enter anything anywhere? i event tried to add modul in "normal mode" (without 'mode:yaml' in configuration) sincer module IS available, but same errors...

Thanks!

**Comment by helto4real** [comment]
Not sure what the problem is. Closing a stale issue.

**Comment by Protoncek** [comment]
Hm… after 2+ years i admit that i don’t know anymore what the problem was…
