### ISSUE TITLE
Crash of the view containing the canvas_jauge-card 

### ISSUE THREAD

**Issue by browetd** [custom-cards/canvas-gauge-card#41]
I am using the last version of "canvas-jauge-card", as well as home assistant on HassOS 5.10 (Pi 4 B 64 bits).
I noticed that on my Huawei tablet (MediaPad M5 Pro) running Android 9 (latest update as well), one view containing a "canvas-jauge-card" was crashing the navigator (I tried: chrome, firefox and opera) as well as the home assistant app.  The crash was happening after a long time (more than 30 minutes) with the screen "Aw Snap, something went wrong".  I removed the card from the view and the crash disappeared.  It is maybe a problem in the definition of the card (see below) or incompatibility with Android 9...

Here is the code of the card (the card is loading correctly):

        - type: custom:canvas-gauge-card
          entity: sensor.smappee_display
          card_height: 230
          shadow_height: 15%
          font_size: 0.9em
          background_color: var(--card-background-color)
          gauge:
            animation: false
            borders: true
            borderShadowWidth: 0
            borderOuterWidth: 0
            borderMiddleWidth: 0
            borderInnerWidth: 0
            type: "radial-gauge"
            width: 220
            height: 220
            minValue: -6000
            maxValue: 14000
            startAngle: 120
            ticksAngle: 200
            valueBox: true
            units: "W"
            colorPlate: "lightgrey"
            majorTicks: ["-6000", " ", "-4000", " ", "-2000", " ", "0", " ", "2000", " ", "4000", " ", "6000", " ", "8000", " ", "10000", " ", "12000", " ", "14000"]
            minorTicks: 2
            strokeTicks: true
            highlights: [{"from": -6000, "to": 0,"color": "lime"}, {"from": 0, "to": 12000,"color": "orange"}, {"from": 12000, "to": 14000,"color": "red"}]

**Comment by helto4real** [comment]
Closing. Stale issue. Could have something to do with animations that should be fixed a few releases ago
