### ISSUE TITLE
Title Color

### ISSUE THREAD

**Issue by pjaxed** [custom-cards/canvas-gauge-card#42]
Hi there.  Great work you are doing here.  Using chrome predominantly and so far all good, accept for the Title color. The user-guide indicates the use of "colorTitle: xxx".  I cannot get it to work.  My gauge Name/Title remains white.  Any pointers would be appreciated. Thank you.

**Comment by pjaxed** [comment]
Sorry just to be clear.  The gauge title font title changes.  It is the "Name" font color I'm struggling with.  I cannot get the shade bar to show, so I am trying to change the font color.

**Comment by pjaxed** [comment]
Hi Tomas,

I eventually came right.  It seems that if you have a few canvas-gauge-cards set up, the background color for all are determined by the first gauge set up.  Meaning if gaueg 1 backgroung color is yellow, regardless for the color you specify, the gauges following will all have yellow as background.

Well done on a great integration.

Regards,

Jako
On 2021/05/09 4:06:32 PM, Tomas Hellström ***@***.***> wrote:
If you could provide a configuration and a screen shot it would be helpful

**Comment by helto4real** [comment]
Ohh thanks!
