### ISSUE TITLE
Handle dates

### ISSUE THREAD

**Issue by AlfredoCABA** [custom-cards/canvas-gauge-card#43]
From Home Assistant architectural design rules: In order to optimize stability and performance of Home Assistant, time based sensors should use only absolute time values (store the date of the event) and not relative time values (seconds from event), so the value doesn’t change each second.

So, lovelace cards should handle countdown to date in JS or handle templates.

Could you point me where in the code this enhancement should be done?

**Comment by helto4real** [comment]
Not sure what you mean. These gauges do not handle dates?

**Comment by AlfredoCABA** [comment]
It now only handle dates after I change this segment of js code:
`this._gauge.value=Math.floor((new Date() - new Date(this._state)) / 86400000),this._gauge.draw()`
