### ISSUE TITLE
Cannot disable drop shadow

### ISSUE THREAD

**Issue by cooperised** [custom-cards/canvas-gauge-card#47]
PR #5 fixed issue #6 by adding a drop shadow to the canvas to match other cards.  However in some circumstances (e.g. when the gauge is part of a stack) it would be useful to be able to switch off the drop shadow.  Currently, for example, if I create a `vertical-stack` or a `custom:stack-in-card` with a canvas gauge and then a history graph below it, the canvas gauge will retain its border.

**Comment by cmckamey** [comment]
bump on this issue...

even with card_mod: style I can't seem to make it go away

**Comment by helto4real** [comment]
Fixed in version 0.8 (defaults to off)
