### ISSUE TITLE
Cannot read Properties of undefined (reading 'width')

### ISSUE THREAD

**Issue by ornative** [custom-cards/canvas-gauge-card#48]
I'm running Homeassistant 2021.9.6, with HACS  1.15.2 and installed canvas-gauge-card through HACS.  When I try to use the card in a Lovelace dashboard I receive this error:

![image](https://user-images.githubusercontent.com/92643138/137765949-96b3265a-437f-4896-913f-fffd3c45dc55.png)

**Comment by amayii0** [comment]
Just got this too.
Also HACS wasn't able to fetch master branch, I had to get 0.4.1

**Comment by amayii0** [comment]
I've been able to get it working @ornative 
This won't work until you set it up.
I used this as base for my setup : https://community.home-assistant.io/t/lovelace-flexible-horseshoe-card-donut-graph-flexible-layout-multiple-entities-actions-animations-including-next-gen-experimental-examples/137850/173?u=amayii0

**Comment by helto4real** [comment]
Thanks for reporting and reporting back how to succeed.
