### ISSUE TITLE
Max gauge value from a sensors value

### ISSUE THREAD

**Issue by mkuhnke71** [custom-cards/canvas-gauge-card#49]
How can I set the maxValue as well as highlights values from sensors in Home Assistant?
Seems I can only hard code these values
Example
  width: 285
  height: 300
  minValue: 0
  maxValue: sensor.meater_probe_internal_2

**Comment by cserem** [comment]
This would be awsome, along with a sensor value for 'valueText' too.

**Comment by jwaz73** [comment]
@mkuhnke71 , the method you are using to address the sensor is not returning the 'text' of the sensor current value but rather the sensor itself.  I'm not sure if this will work with this card but I have used the following in other cards where I want to put the current value of the sensor in a title or headline.  In your example:
`maxValue: {{ states('sensor.meater_probe_internal_2') }}`

I just tried this with a temperature sensor and it did not result in an error but it might take some work to make sense of the gauge reading.
