### ISSUE TITLE
Half gauge not working

### ISSUE THREAD

**Issue by riesi77** [custom-cards/canvas-gauge-card#52]
The template code of displaying a half gauge with processor% still displays a full gauge (see screenshot). I'm using HA 2022.11.
![image](https://user-images.githubusercontent.com/67387975/201344197-f7f42b3c-8c42-4a7e-9c4f-5b128a8cdf2c.png)

Card configuration code is:
`type: custom:canvas-gauge-card
entity: sensor.processor_use
name: Processor (%)
card_height: 145
shadow_height: 15%
font_size: 1em
gauge:
  type: radial-gauge
  width: 220
  height: 220
  borderShadowWidth: 0
  borderOuterWidth: 0
  borderMiddleWidth: 0
  borderInnerWidth: 0
  minValue: 0
  maxValue: 100
  startAngle: 90
  ticksAngle: 180
  valueBox: false
  majorTicks:
    - '0'
    - '10'
    - '20'
    - '30'
    - '40'
    - '50'
    - '60'
    - '70'
    - '80'
    - '90'
    - '100'
  minorTicks: 2
  strokeTicks: true
  highlights:
    - from: 80
      to: 100
      color: rgba(200, 50, 50, .75)
  borders: false
`

**Comment by Guenni75** [comment]
Same here. Half gauge isn't working.

**Comment by poudenes** [comment]
Same issue

**Comment by mutzl** [comment]
What browser and what device are you running the card?
What is the layout setting of the page?

I got complete different results with wallpanel on fire tablet compared to desktop browser.

**Comment by mutzl** [comment]
@helto4real just provided an upgrade to V0.6, which fixed it for me!
Thanks man!
