### ISSUE TITLE
Can't get title to display ?

### ISSUE THREAD

**Issue by SteveBrailsord** [custom-cards/canvas-gauge-card#55]
Can't get title to display - tried every which way i can think of.
This is my config in UI-Config yaml
![image](https://user-images.githubusercontent.com/115092743/224983033-80745736-4091-4cb6-9988-377f99466bce.png)

type: custom:canvas-gauge-card
entity: sensor.pv_power_now_watts
title: Solar power now
gauge:
  type: radial-gauge
  width: 210
  height: 210
  borderShadowWidth: 10
  borderOuterWidth: 0
  borderMiddleWidth: 0
  borderInnerWidth: 0
  minValue: 0
  maxValue: 7000
  startAngle: 40
  ticksAngle: 280
  valueBox: true
  units: Watts
  majorTicks:
    - '0'
    - '1000'
    - '2000'
    - '3000'
    - '4000'
    - '5000'
    - '6000'
    - '7000'
  minorTicks: 2
  strokeTicks: true
  highlights:
    - from: 0
      to: 1500
      color: rgba(200, 50, 50, .75)
  borders: false

**Comment by helto4real** [comment]
Use `valueBox: true` should work. Make sure you do not display half gauge since the valuebox will then be hidden. Cannon reproduce.
