### ISSUE TITLE
Does not work?

### ISSUE THREAD

**Issue by PalmMx** [custom-cards/canvas-gauge-card#8]
I have put the js files in the www folder and I have inserted the resources code in top of the Raw config editor.
Then I try to paste some of the examples from here into a Manual Card and in the Raw config editor, but I'm only getting error messages.
I'm not using yaml mode.

Doesn't this Custom card work with HASS 0.87?

Or since I assume my knowledge about Custom cards is almost zero, can someone please submit some example code that is actually working?

The readme file here seems not to be updated to the new standard Lovelace configurations.

Thank you in advance!

**Comment by flyboy013** [comment]
I'm having the same issue.  I've tried with the the version of gauge.min.js that I already had as well as the specific version that this card has on github.  HA Lovelace states that the custom card doesn't exist.  It in my www folder along with my other custom cards and I've added the resource in the lovelace ui file.

**Comment by PalmMx** [comment]
> I'm having the same issue. I've tried with the the version of gauge.min.js that I already had as well as the specific version that this card has on github. HA Lovelace states that the custom card doesn't exist. It in my www folder along with my other custom cards and I've added the resource in the lovelace ui file.

It's workning now. This is my setup (Hass.io 0.89.1)
Raw Config editor:
```
resources:
  - type: module
    url: /local/canvas-gauge-card.js
title: Home
```

The four files (including the two .js files) are saved in this folder:
`\config\www\`

I also cleared the cache and other stuff in the browser (Chrome) and I needed to refresh the Home Assistant iOS app to be able to show the gauge cards also on my iPhone.
